### ISSUE TITLE
Wrong mock being triggered when first argument is the same

### ISSUE THREAD

**Issue by PatrickF1** [IlanCosman/clownfish#1]
Steps to repro
```
$ mock commandline "--current-token --replace" "echo 1"
$ commandline --current-token --replace
1
$ mock commandline "--current-token" "echo 2"
$ commandline --current-token --replace
2
```
Exectation: I was expecting the last call to print 1, not 2.

**Comment by IlanCosman** [comment]
Yah the way I wrote it would do that, since it takes the most general one first. I'll have to do it backwards.

**Comment by PatrickF1** [comment]
Wow you are so fast! Thanks for supporting me

**Comment by IlanCosman** [comment]
Done!

**Comment by PatrickF1** [comment]
Thanks! Now my tests pass! Check out my pretty complicated usage of Clownfish in https://github.com/PatrickF1/fzf.fish/pull/82
